export default {
    PRIMARY:"#74475D",
    SECONDARY:"#74475D",
    INPUT:"#ECEDEC",
    CHAT:{
        sent:"#718D93",
        rec:"#5DA392",
        title:"#ffffff",
        text:"#ffffff",
        info:"#87CEFA",
        name:"#A9A9A9"
    },
    TIMESTAMP:"#696969",
    BACKGROUND:"#ECEDEC",
    NETINFO:{
        connected:"#CD5C5C",
        connecting:"#BBBE64",
        notConnected:"#47745E",
        text:"#F2F2F2"
    },
    BUTTON:"#ECEDEC",
    TEXT:"#FFF",
    HOLDERTEXT:"#696969",
    TITLE:"#FFF"
}